### ISSUE TITLE
error running example in local Docker environment

### ISSUE THREAD

**Issue by Laurian** [metrue/fx#613] opened 2021-05-31 11:06 UTC
I tried this on Docker on Mac, fx installed via brew, running from download of this repo:

```
➜  fx-master fx --version
fx version 0.9.47
```

```
➜  fx-master fx up --name hello ./examples/functions/JavaScript/func.js 
2021/05/31 14:03:04  info provisioning localhost ...
Starting building
2 / 100 [-->______________________________________________________________________________________________________________] 2.00% ? p/s
Starting deploying hello
1 / 100 [->_______________________________________________________________________________________________________________] 1.00% ? p/s
deploying hello: ✗
*****************
create container request failed: request http://localhost:8866/v1.41/containers/create?name=hello ({"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"3000/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":null,"Image":"hello-20210531140308:latest","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":null,"HostConfig":{"Binds":null,"ContainerIDFile":"","LogConfig":{"Type":"","Config":null},"NetworkMode":"","PortBindings":{"3000/tcp":[{"HostIp":"0.0.0.0","HostPort":"54722"}]},"RestartPolicy":{"Name":"","MaximumRetryCount":0},"AutoRemove":false,"VolumeDriver":"","VolumesFrom":null,"CapAdd":null,"CapDrop":null,"Capabilities":null,"Dns":null,"DnsOptions":null,"DnsSearch":null,"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","Cgroup":"","Links":null,"OomScoreAdj":0,"PidMode":"","Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"SecurityOpt":null,"UTSMode":"","UsernsMode":"","ShmSize":0,"ConsoleSize":[0,0],"Isolation":"","CpuShares":0,"Memory":0,"NanoCpus":0,"CgroupParent":"","BlkioWeight":0,"BlkioWeightDevice":null,"BlkioDeviceReadBps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteIOps":null,"CpuPeriod":0,"CpuQuota":0,"CpuRealtimePeriod":0,"CpuRealtimeRuntime":0,"CpusetCpus":"","CpusetMems":"","Devices":null,"DeviceCgroupRules":null,"DiskQuota":0,"KernelMemory":0,"KernelMemoryTCP":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":null,"OomKillDisable":null,"PidsLimit":null,"Ulimits":null,"CpuCount":0,"CpuPercent":0,"IOMaximumIOps":0,"IOMaximumBandwidth":0,"MaskedPaths":null,"ReadonlyPaths":null},"NetworkingConfig":{"EndpointsConfig":{"fx-net":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"bc5c2deb6140256dbebbe0a0cad987aad76a73f0ae2e3ef7371020d4de2573de","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"","DriverOpts":null}}}}) failed: 404 - 404 Not Found
*****************
```

```
➜  fx-master docker ps
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS          PORTS                    NAMES
b2f37b612a3a   bobrik/socat   "socat TCP-LISTEN:12…"   15 seconds ago   Up 14 seconds   0.0.0.0:8866->1234/tcp   fx-agent
```

**Comment by metrue** [comment] 2021-06-01 03:56
It looks like the image had not been built somehow,  could you try `DEBUG=1 fx up examples/functions/JavaScript/func.js` and check the output log?

**Comment by Laurian** [comment] 2021-06-01 05:39
```
➜  fx-master DEBUG=1 fx up examples/functions/JavaScript/func.js
2021/06/01 08:32:47  info provisioning localhost ...
Starting building
2021/06/01 08:32:51  info {"message":"Cannot locate specified Dockerfile: Dockerfile"}
3 / 100 [--->_________________________________________________________________________________________________] 3.00% ? p/s
Starting deploying c71bc15d-18ac-49ef-b632-4f11567639fe
1 / 100 [->___________________________________________________________________________________________________] 1.00% ? p/s
deploying c71bc15d-18ac-49ef-b632-4f11567639fe: ✗
*****************
create container request failed: request http://localhost:8866/v1.41/containers/create?name=c71bc15d-18ac-49ef-b632-4f11567639fe ({"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"3000/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":null,"Image":"c71bc15d-18ac-49ef-b632-4f11567639fe-20210601083251:latest","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":null,"HostConfig":{"Binds":null,"ContainerIDFile":"","LogConfig":{"Type":"","Config":null},"NetworkMode":"","PortBindings":{"3000/tcp":[{"HostIp":"0.0.0.0","HostPort":"51000"}]},"RestartPolicy":{"Name":"","MaximumRetryCount":0},"AutoRemove":false,"VolumeDriver":"","VolumesFrom":null,"CapAdd":null,"CapDrop":null,"Capabilities":null,"Dns":null,"DnsOptions":null,"DnsSearch":null,"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","Cgroup":"","Links":null,"OomScoreAdj":0,"PidMode":"","Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"SecurityOpt":null,"UTSMode":"","UsernsMode":"","ShmSize":0,"ConsoleSize":[0,0],"Isolation":"","CpuShares":0,"Memory":0,"NanoCpus":0,"CgroupParent":"","BlkioWeight":0,"BlkioWeightDevice":null,"BlkioDeviceReadBps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteIOps":null,"CpuPeriod":0,"CpuQuota":0,"CpuRealtimePeriod":0,"CpuRealtimeRuntime":0,"CpusetCpus":"","CpusetMems":"","Devices":null,"DeviceCgroupRules":null,"DiskQuota":0,"KernelMemory":0,"KernelMemoryTCP":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":null,"OomKillDisable":null,"PidsLimit":null,"Ulimits":null,"CpuCount":0,"CpuPercent":0,"IOMaximumIOps":0,"IOMaximumBandwidth":0,"MaskedPaths":null,"ReadonlyPaths":null},"NetworkingConfig":{"EndpointsConfig":{"fx-net":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"bc5c2deb6140256dbebbe0a0cad987aad76a73f0ae2e3ef7371020d4de2573de","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"","DriverOpts":null}}}}) failed: 404 - 404 Not Found
*****************
```

Interesting, `Cannot locate specified Dockerfile: Dockerfile`… well, there is none in `examples/*`, I suppose it should get the one in `driver/docker/fixture` somehow? (I haven't dug into the internals yet)

**Comment by bad33ndj3** [comment] 2021-06-07 13:02
I have the same issue on raspbian

**Comment by metrue** [comment] 2021-06-08 08:11
@bad33ndj3 @Laurian Thanks for reporting this issue, I can reproduce it on ubuntu, will update the fix soon.

**Comment by metrue** [comment] 2021-06-09 02:14
@Laurian @bad33ndj3 
Fix has been shipped in version 0.9.48, please try it, let me know if it's still broken.

**Comment by Laurian** [comment] 2021-06-09 08:10
yay! works on macOS:
```
➜  fx-master fx up --name hello ./examples/functions/JavaScript/func.js
2021/06/09 11:04:00  info provisioning localhost ...
Starting building
100 / 100 [---------------------------------------------------------------------------------------------------------] 100.00% 9 p/s
Starting deploying hello
100 / 100 [--------------------------------------------------------------------------------------------------------] 100.00% 17 p/s
+------------------------------------------------------------------+--------+---------------+
|                                ID                                |  NAME  |   ENDPOINT    |
+------------------------------------------------------------------+--------+---------------+
| 60262781e4f14e390667d491992e283b19b523569425eacdaee0a604c8ce71ce | /hello | 0.0.0.0:58741 |
+------------------------------------------------------------------+--------+---------------+
➜  fx-master curl http://localhost:58741
hello world%
```

and works on Ubuntu too:
```
# DEBUG=1 fx up examples/functions/JavaScript/func.js
2021/06/09 08:07:44  info provisioning localhost ...
Starting building
[...]
Starting deploying fe8b2d0c-eae8-4227-aeea-ca3a4209d1e3
79 / 100 [----------------------------------------------------------------------------------->______________________] 79.00% 21 p/s
+------------------------------------------------------------------+---------------------------------------+---------------+
|                                ID                                |                 NAME                  |   ENDPOINT    |
+------------------------------------------------------------------+---------------------------------------+---------------+
| 10d0b300165d51f6e2407178fc79f761049cbe08850c245d83e5fdef5304d61f | /fe8b2d0c-eae8-4227-aeea-ca3a4209d1e3 | 0.0.0.0:44015 |
+------------------------------------------------------------------+---------------------------------------+---------------+
# curl http://localhost:44015
hello world 

```

**Comment by metrue** [comment] 2021-06-09 08:16
awesome, free to re-open it if you find any issue.

**Closed by metrue** 2021-06-09 08:16 UTC
Labels: bug
